# Generated by Django 6.1 on 2026-09-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Serviço')),
                ('preco', models.IntegerField(verbose_name='Preço em Kz')),
                ('descricao_curta', models.CharField(max_length=200, verbose_name='Descrição Curta')),
                ('descricao_completa', models.TextField(verbose_name='O que inclui')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Visível no Site')),
            ],
            options={
                'verbose_name': 'Serviço e Preço',
                'verbose_name_plural': 'Serviços e Preços',
                'ordering': ['ordem'],
            },
        ),
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ['-data_envio'], 'verbose_name': 'Mensagem de Contato', 'verbose_name_plural': 'Mensagens de Contato'},
        ),
        migrations.AlterField(
            model_name='contato',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='mensagem',
            field=models.TextField(verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
